import json

from app.log_models import LogAnalyzeRequest
from app.resource_assignment_analyzer import analyze_resource_assignment_evidence


def test_guided_resource_assignment_evidence_returns_missing_assignment_finding():
    content = json.dumps(
        {
            "timestamp": "2026-07-07T11:00:00Z",
            "affected_user": "sample.user@contoso.invalid",
            "resource": "Engineering SharePoint Site",
            "application": "SharePoint Online",
            "authentication_outcome": "success",
            "assignment_present": False,
            "expected_access_confirmed": True,
            "conditional_access_status": "success",
            "mfa_result": "satisfied",
            "failure_reason": "User receives access denied when opening the specific resource.",
            "evidence_checked": [
                "Entra sign-in result checked",
                "Conditional Access result checked",
                "MFA result checked",
                "Resource owner or ticket confirms expected access",
                "Resource membership or assignment checked",
            ],
        }
    )

    analysis = analyze_resource_assignment_evidence(
        LogAnalyzeRequest(
            source_type="resource_assignment_json",
            affected_user="sample.user@contoso.invalid",
            affected_service="Engineering SharePoint Site",
            content=content,
            notes="Generated by the guided resource assignment form.",
        )
    )

    assert analysis.status == "findings"
    assert analysis.primary_finding is not None
    assert analysis.primary_finding["rule_id"] == "RESOURCE_ASSIGNMENT_OR_GROUP_MEMBERSHIP_MISSING_OR_UNCONFIRMED"
    assert analysis.primary_finding["confidence"] == "high"
    assert analysis.normalized_events[0].event_outcome == "failure"
    assert "Resource assignment evidence is missing or negative." in analysis.detected_patterns[0].evidence
